# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'i3mainWindow.ui'
##
## Created by: Qt User Interface Compiler version 6.8.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QGroupBox, QHBoxLayout,
    QHeaderView, QMainWindow, QMenu, QMenuBar,
    QSizePolicy, QSplitter, QStatusBar, QTabWidget,
    QTableView, QToolBar, QTreeView, QWidget)

from i3viewer.i3vtkWidget import i3vtkWidget
import i3viewer.icons_rc

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        if not mainWindow.objectName():
            mainWindow.setObjectName(u"mainWindow")
        mainWindow.resize(1002, 666)
        icon = QIcon()
        icon.addFile(u":/icons/3dviewer.ico", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        mainWindow.setWindowIcon(icon)
        mainWindow.setIconSize(QSize(22, 22))
        self.actionOpenFile = QAction(mainWindow)
        self.actionOpenFile.setObjectName(u"actionOpenFile")
        self.actionOpenFile.setEnabled(True)
        icon1 = QIcon()
        icon1.addFile(u":/icons/open.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionOpenFile.setIcon(icon1)
        self.actionExit = QAction(mainWindow)
        self.actionExit.setObjectName(u"actionExit")
        icon2 = QIcon()
        icon2.addFile(u":/icons/exit.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionExit.setIcon(icon2)
        self.actionHelp = QAction(mainWindow)
        self.actionHelp.setObjectName(u"actionHelp")
        icon3 = QIcon()
        icon3.addFile(u":/icons/help.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionHelp.setIcon(icon3)
        self.actionFront = QAction(mainWindow)
        self.actionFront.setObjectName(u"actionFront")
        icon4 = QIcon()
        icon4.addFile(u":/icons/front.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionFront.setIcon(icon4)
        self.actionFront.setMenuRole(QAction.NoRole)
        self.actionBack = QAction(mainWindow)
        self.actionBack.setObjectName(u"actionBack")
        icon5 = QIcon()
        icon5.addFile(u":/icons/back.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionBack.setIcon(icon5)
        self.actionBack.setMenuRole(QAction.NoRole)
        self.actionTop = QAction(mainWindow)
        self.actionTop.setObjectName(u"actionTop")
        icon6 = QIcon()
        icon6.addFile(u":/icons/top.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionTop.setIcon(icon6)
        self.actionTop.setMenuRole(QAction.NoRole)
        self.actionBottom = QAction(mainWindow)
        self.actionBottom.setObjectName(u"actionBottom")
        icon7 = QIcon()
        icon7.addFile(u":/icons/bottom.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionBottom.setIcon(icon7)
        self.actionBottom.setMenuRole(QAction.NoRole)
        self.actionLeft = QAction(mainWindow)
        self.actionLeft.setObjectName(u"actionLeft")
        icon8 = QIcon()
        icon8.addFile(u":/icons/left.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionLeft.setIcon(icon8)
        self.actionLeft.setMenuRole(QAction.NoRole)
        self.actionRight = QAction(mainWindow)
        self.actionRight.setObjectName(u"actionRight")
        icon9 = QIcon()
        icon9.addFile(u":/icons/right.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionRight.setIcon(icon9)
        self.actionRight.setMenuRole(QAction.NoRole)
        self.actionIso = QAction(mainWindow)
        self.actionIso.setObjectName(u"actionIso")
        icon10 = QIcon()
        icon10.addFile(u":/icons/iso.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionIso.setIcon(icon10)
        self.actionIso.setMenuRole(QAction.NoRole)
        self.actionFit = QAction(mainWindow)
        self.actionFit.setObjectName(u"actionFit")
        icon11 = QIcon()
        icon11.addFile(u":/icons/resize.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionFit.setIcon(icon11)
        self.actionFit.setMenuRole(QAction.NoRole)
        self.actionExport = QAction(mainWindow)
        self.actionExport.setObjectName(u"actionExport")
        icon12 = QIcon()
        icon12.addFile(u":/icons/export.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionExport.setIcon(icon12)
        self.actionPlus = QAction(mainWindow)
        self.actionPlus.setObjectName(u"actionPlus")
        icon13 = QIcon()
        icon13.addFile(u":/icons/plus.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionPlus.setIcon(icon13)
        self.actionMinus = QAction(mainWindow)
        self.actionMinus.setObjectName(u"actionMinus")
        icon14 = QIcon()
        icon14.addFile(u":/icons/minus.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionMinus.setIcon(icon14)
        self.actionHeatMap = QAction(mainWindow)
        self.actionHeatMap.setObjectName(u"actionHeatMap")
        self.actionHeatMap.setCheckable(True)
        icon15 = QIcon()
        icon15.addFile(u":/icons/heatmap.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionHeatMap.setIcon(icon15)
        self.actionBackward = QAction(mainWindow)
        self.actionBackward.setObjectName(u"actionBackward")
        icon16 = QIcon()
        icon16.addFile(u":/icons/backward.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionBackward.setIcon(icon16)
        self.labelPeriod = QAction(mainWindow)
        self.labelPeriod.setObjectName(u"labelPeriod")
        self.actionForward = QAction(mainWindow)
        self.actionForward.setObjectName(u"actionForward")
        icon17 = QIcon()
        icon17.addFile(u":/icons/forward.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionForward.setIcon(icon17)
        self.actionHeatMapCfg = QAction(mainWindow)
        self.actionHeatMapCfg.setObjectName(u"actionHeatMapCfg")
        icon18 = QIcon()
        icon18.addFile(u":/icons/heatmapcfg.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionHeatMapCfg.setIcon(icon18)
        self.actionUnpick = QAction(mainWindow)
        self.actionUnpick.setObjectName(u"actionUnpick")
        self.actionUnpick.setCheckable(True)
        icon19 = QIcon()
        icon19.addFile(u":/icons/unpick.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionUnpick.setIcon(icon19)
        self.actionPolyLabel = QAction(mainWindow)
        self.actionPolyLabel.setObjectName(u"actionPolyLabel")
        self.actionPolyLabel.setCheckable(True)
        icon20 = QIcon()
        icon20.addFile(u":/icons/polyabc.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionPolyLabel.setIcon(icon20)
        self.actionPointLabel = QAction(mainWindow)
        self.actionPointLabel.setObjectName(u"actionPointLabel")
        self.actionPointLabel.setCheckable(True)
        icon21 = QIcon()
        icon21.addFile(u":/icons/pointabc.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionPointLabel.setIcon(icon21)
        self.actionSurface = QAction(mainWindow)
        self.actionSurface.setObjectName(u"actionSurface")
        self.actionSurface.setCheckable(True)
        icon22 = QIcon()
        icon22.addFile(u":/icons/surface.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionSurface.setIcon(icon22)
        self.actionWireframe = QAction(mainWindow)
        self.actionWireframe.setObjectName(u"actionWireframe")
        self.actionWireframe.setCheckable(True)
        icon23 = QIcon()
        icon23.addFile(u":/icons/wireframe.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionWireframe.setIcon(icon23)
        self.actionSurfaceCfg = QAction(mainWindow)
        self.actionSurfaceCfg.setObjectName(u"actionSurfaceCfg")
        icon24 = QIcon()
        icon24.addFile(u":/icons/surfacecfg.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionSurfaceCfg.setIcon(icon24)
        self.actionContour = QAction(mainWindow)
        self.actionContour.setObjectName(u"actionContour")
        self.actionContour.setCheckable(True)
        icon25 = QIcon()
        icon25.addFile(u":/icons/contour.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionContour.setIcon(icon25)
        self.actionAbout = QAction(mainWindow)
        self.actionAbout.setObjectName(u"actionAbout")
        self.centralwidget = QWidget(mainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.horizontalLayout_3 = QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.horizontalLayout_4 = QHBoxLayout(self.tab)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.groupBoxGraph = QGroupBox(self.tab)
        self.groupBoxGraph.setObjectName(u"groupBoxGraph")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.groupBoxGraph.sizePolicy().hasHeightForWidth())
        self.groupBoxGraph.setSizePolicy(sizePolicy)
        self.horizontalLayout = QHBoxLayout(self.groupBoxGraph)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.splitter = QSplitter(self.groupBoxGraph)
        self.splitter.setObjectName(u"splitter")
        self.splitter.setOrientation(Qt.Horizontal)
        self.tableFrame = QFrame(self.splitter)
        self.tableFrame.setObjectName(u"tableFrame")
        self.horizontalLayout_2 = QHBoxLayout(self.tableFrame)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.treeView = QTreeView(self.tableFrame)
        self.treeView.setObjectName(u"treeView")

        self.horizontalLayout_2.addWidget(self.treeView)

        self.splitter.addWidget(self.tableFrame)
        self.qvtkWidget = i3vtkWidget(self.splitter)
        self.qvtkWidget.setObjectName(u"qvtkWidget")
        sizePolicy.setHeightForWidth(self.qvtkWidget.sizePolicy().hasHeightForWidth())
        self.qvtkWidget.setSizePolicy(sizePolicy)
        self.qvtkWidget.setMinimumSize(QSize(300, 300))
        self.splitter.addWidget(self.qvtkWidget)

        self.horizontalLayout.addWidget(self.splitter)


        self.horizontalLayout_4.addWidget(self.groupBoxGraph)

        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.horizontalLayout_5 = QHBoxLayout(self.tab_2)
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.tableViewPolylines = QTableView(self.tab_2)
        self.tableViewPolylines.setObjectName(u"tableViewPolylines")

        self.horizontalLayout_5.addWidget(self.tableViewPolylines)

        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.horizontalLayout_6 = QHBoxLayout(self.tab_3)
        self.horizontalLayout_6.setObjectName(u"horizontalLayout_6")
        self.tableViewPoints = QTableView(self.tab_3)
        self.tableViewPoints.setObjectName(u"tableViewPoints")

        self.horizontalLayout_6.addWidget(self.tableViewPoints)

        self.tabWidget.addTab(self.tab_3, "")

        self.horizontalLayout_3.addWidget(self.tabWidget)

        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(mainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1002, 24))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(mainWindow)
        self.statusbar.setObjectName(u"statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.mainToolBar = QToolBar(mainWindow)
        self.mainToolBar.setObjectName(u"mainToolBar")
        self.mainToolBar.setOrientation(Qt.Horizontal)
        self.mainToolBar.setIconSize(QSize(22, 22))
        mainWindow.addToolBar(Qt.ToolBarArea.TopToolBarArea, self.mainToolBar)
        self.viewToolBar = QToolBar(mainWindow)
        self.viewToolBar.setObjectName(u"viewToolBar")
        mainWindow.addToolBar(Qt.ToolBarArea.TopToolBarArea, self.viewToolBar)
        self.heatmapToolBar = QToolBar(mainWindow)
        self.heatmapToolBar.setObjectName(u"heatmapToolBar")
        mainWindow.addToolBar(Qt.ToolBarArea.TopToolBarArea, self.heatmapToolBar)
        self.selectionToolBar = QToolBar(mainWindow)
        self.selectionToolBar.setObjectName(u"selectionToolBar")
        mainWindow.addToolBar(Qt.ToolBarArea.TopToolBarArea, self.selectionToolBar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menuFile.addAction(self.actionOpenFile)
        self.menuFile.addAction(self.actionPlus)
        self.menuFile.addAction(self.actionMinus)
        self.menuFile.addAction(self.actionExport)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.mainToolBar.addAction(self.actionOpenFile)
        self.mainToolBar.addAction(self.actionPlus)
        self.mainToolBar.addAction(self.actionMinus)
        self.mainToolBar.addAction(self.actionExport)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionHelp)
        self.mainToolBar.addSeparator()
        self.viewToolBar.addAction(self.actionFront)
        self.viewToolBar.addAction(self.actionBack)
        self.viewToolBar.addAction(self.actionTop)
        self.viewToolBar.addAction(self.actionBottom)
        self.viewToolBar.addAction(self.actionLeft)
        self.viewToolBar.addAction(self.actionRight)
        self.viewToolBar.addSeparator()
        self.viewToolBar.addAction(self.actionIso)
        self.viewToolBar.addAction(self.actionFit)
        self.viewToolBar.addSeparator()
        self.heatmapToolBar.addAction(self.actionHeatMapCfg)
        self.heatmapToolBar.addAction(self.actionHeatMap)
        self.heatmapToolBar.addSeparator()
        self.heatmapToolBar.addAction(self.actionBackward)
        self.heatmapToolBar.addAction(self.labelPeriod)
        self.heatmapToolBar.addAction(self.actionForward)
        self.selectionToolBar.addAction(self.actionUnpick)
        self.selectionToolBar.addAction(self.actionPolyLabel)
        self.selectionToolBar.addAction(self.actionPointLabel)
        self.selectionToolBar.addSeparator()
        self.selectionToolBar.addAction(self.actionContour)
        self.selectionToolBar.addAction(self.actionSurface)
        self.selectionToolBar.addAction(self.actionWireframe)
        self.selectionToolBar.addAction(self.actionSurfaceCfg)
        self.selectionToolBar.addSeparator()

        self.retranslateUi(mainWindow)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(mainWindow)
    # setupUi

    def retranslateUi(self, mainWindow):
        mainWindow.setWindowTitle(QCoreApplication.translate("mainWindow", u"Interactive 3D Model Viewer", None))
        self.actionOpenFile.setText(QCoreApplication.translate("mainWindow", u"Open File...", None))
#if QT_CONFIG(shortcut)
        self.actionOpenFile.setShortcut(QCoreApplication.translate("mainWindow", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.actionExit.setText(QCoreApplication.translate("mainWindow", u"Exit", None))
#if QT_CONFIG(shortcut)
        self.actionExit.setShortcut(QCoreApplication.translate("mainWindow", u"Ctrl+X", None))
#endif // QT_CONFIG(shortcut)
        self.actionHelp.setText(QCoreApplication.translate("mainWindow", u"Help", None))
#if QT_CONFIG(shortcut)
        self.actionHelp.setShortcut(QCoreApplication.translate("mainWindow", u"Ctrl+H", None))
#endif // QT_CONFIG(shortcut)
        self.actionFront.setText(QCoreApplication.translate("mainWindow", u"Front", None))
        self.actionBack.setText(QCoreApplication.translate("mainWindow", u"Back", None))
        self.actionTop.setText(QCoreApplication.translate("mainWindow", u"Top", None))
        self.actionBottom.setText(QCoreApplication.translate("mainWindow", u"Bottom", None))
        self.actionLeft.setText(QCoreApplication.translate("mainWindow", u"Left", None))
        self.actionRight.setText(QCoreApplication.translate("mainWindow", u"Right", None))
        self.actionIso.setText(QCoreApplication.translate("mainWindow", u"Iso", None))
        self.actionFit.setText(QCoreApplication.translate("mainWindow", u"Fit", None))
        self.actionExport.setText(QCoreApplication.translate("mainWindow", u"Export", None))
#if QT_CONFIG(tooltip)
        self.actionExport.setToolTip(QCoreApplication.translate("mainWindow", u"Export", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionExport.setShortcut(QCoreApplication.translate("mainWindow", u"Ctrl+E", None))
#endif // QT_CONFIG(shortcut)
        self.actionPlus.setText(QCoreApplication.translate("mainWindow", u"Append File...", None))
#if QT_CONFIG(shortcut)
        self.actionPlus.setShortcut(QCoreApplication.translate("mainWindow", u"Ctrl+A", None))
#endif // QT_CONFIG(shortcut)
        self.actionMinus.setText(QCoreApplication.translate("mainWindow", u"Close all", None))
#if QT_CONFIG(tooltip)
        self.actionMinus.setToolTip(QCoreApplication.translate("mainWindow", u"Close All Files", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionMinus.setShortcut(QCoreApplication.translate("mainWindow", u"Ctrl+Q", None))
#endif // QT_CONFIG(shortcut)
        self.actionHeatMap.setText(QCoreApplication.translate("mainWindow", u"HeatMap", None))
#if QT_CONFIG(tooltip)
        self.actionHeatMap.setToolTip(QCoreApplication.translate("mainWindow", u"Active HeatMap", None))
#endif // QT_CONFIG(tooltip)
        self.actionBackward.setText(QCoreApplication.translate("mainWindow", u"Backward", None))
#if QT_CONFIG(tooltip)
        self.actionBackward.setToolTip(QCoreApplication.translate("mainWindow", u"Backward Period", None))
#endif // QT_CONFIG(tooltip)
        self.labelPeriod.setText(QCoreApplication.translate("mainWindow", u"P: 0/0", None))
#if QT_CONFIG(tooltip)
        self.labelPeriod.setToolTip(QCoreApplication.translate("mainWindow", u"Period Value", None))
#endif // QT_CONFIG(tooltip)
        self.actionForward.setText(QCoreApplication.translate("mainWindow", u"Forward", None))
#if QT_CONFIG(tooltip)
        self.actionForward.setToolTip(QCoreApplication.translate("mainWindow", u"Forward Period", None))
#endif // QT_CONFIG(tooltip)
        self.actionHeatMapCfg.setText(QCoreApplication.translate("mainWindow", u"HeatMapCfg", None))
#if QT_CONFIG(tooltip)
        self.actionHeatMapCfg.setToolTip(QCoreApplication.translate("mainWindow", u"HeatMap Configuration", None))
#endif // QT_CONFIG(tooltip)
        self.actionUnpick.setText(QCoreApplication.translate("mainWindow", u"Unpick", None))
#if QT_CONFIG(tooltip)
        self.actionUnpick.setToolTip(QCoreApplication.translate("mainWindow", u"Disable Picker", None))
#endif // QT_CONFIG(tooltip)
        self.actionPolyLabel.setText(QCoreApplication.translate("mainWindow", u"PolyLabel", None))
#if QT_CONFIG(tooltip)
        self.actionPolyLabel.setToolTip(QCoreApplication.translate("mainWindow", u"Show Polyline Label", None))
#endif // QT_CONFIG(tooltip)
        self.actionPointLabel.setText(QCoreApplication.translate("mainWindow", u"PointLabel", None))
#if QT_CONFIG(tooltip)
        self.actionPointLabel.setToolTip(QCoreApplication.translate("mainWindow", u"Show Point Label", None))
#endif // QT_CONFIG(tooltip)
        self.actionSurface.setText(QCoreApplication.translate("mainWindow", u"Surface", None))
#if QT_CONFIG(tooltip)
        self.actionSurface.setToolTip(QCoreApplication.translate("mainWindow", u"Surface Reconstruction", None))
#endif // QT_CONFIG(tooltip)
        self.actionWireframe.setText(QCoreApplication.translate("mainWindow", u"Wireframe", None))
#if QT_CONFIG(tooltip)
        self.actionWireframe.setToolTip(QCoreApplication.translate("mainWindow", u"Wireframe Reconstruction", None))
#endif // QT_CONFIG(tooltip)
        self.actionSurfaceCfg.setText(QCoreApplication.translate("mainWindow", u"SurfaceCfg", None))
#if QT_CONFIG(tooltip)
        self.actionSurfaceCfg.setToolTip(QCoreApplication.translate("mainWindow", u"Surface Configuration...", None))
#endif // QT_CONFIG(tooltip)
        self.actionContour.setText(QCoreApplication.translate("mainWindow", u"Contour", None))
#if QT_CONFIG(tooltip)
        self.actionContour.setToolTip(QCoreApplication.translate("mainWindow", u"Show Contour Lines", None))
#endif // QT_CONFIG(tooltip)
        self.actionAbout.setText(QCoreApplication.translate("mainWindow", u"About...", None))
        self.groupBoxGraph.setTitle(QCoreApplication.translate("mainWindow", u"Views", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("mainWindow", u"Viewer", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("mainWindow", u"Polylines", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("mainWindow", u"Points", None))
        self.menuFile.setTitle(QCoreApplication.translate("mainWindow", u"File", None))
        self.menuHelp.setTitle(QCoreApplication.translate("mainWindow", u"Help", None))
        self.mainToolBar.setWindowTitle(QCoreApplication.translate("mainWindow", u"Main Tool Bar", None))
        self.viewToolBar.setWindowTitle(QCoreApplication.translate("mainWindow", u"View Tool Bar", None))
        self.heatmapToolBar.setWindowTitle(QCoreApplication.translate("mainWindow", u"HeatMap Tool Bar", None))
        self.selectionToolBar.setWindowTitle(QCoreApplication.translate("mainWindow", u"Selection Tool Bar", None))
    # retranslateUi

